[package]
name = "audit_bounty"
version = "0.1.0"
edition = "2018"

[dependencies]
solana-program = "1.7.0"
borsh = "0.9.1"
borsh-derive = "0.9.1"  
thiserror = "1.0.24"
spl-token = { version = "3.1.1", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"] 