[features]
seeds = false
skip-lint = false

[programs.localnet]
audit_bounty = "BUPQa6bZdMcos6JnNmiaqwywPrBsS9iYVagH2TcBKSXi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.29.0" 